version: '3.2'

services:
  moon:
    build:
      context: .
    ports:
    - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ENV: dev

  mysql:
    image: mysql:8.0
    cap_add:
      - CAP_SYS_NICE
    container_name: moon-database
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'moon'
    ports:
      - 3306:3306
    volumes:
      - ./sql/database.sql:/docker-entrypoint-initdb.d/init.sql