version: '3.8'

services:
  moon:
    container_name: "moon"
    build:
      context: .
    ports:
    - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    environment:
      ENV: dev
      MYSQL_HOST: moon_database
      MYSQL_PORT: 3306

  mysql:
    image: mysql:8.0
    cap_add:
      - CAP_SYS_NICE
    container_name: moon_database
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'moon'
    ports:
      - 3306:3306
    volumes:
      - ./sql/database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  zookeeper:
    container_name: moon-zookepeer
    image: confluent/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: moon-kafka
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      - KAFKA_ADVERTISED_HOST_NAME
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_LOG_RETENTION_HOURS=1
      - KAFKA_MESSAGE_MAX_BYTES=10000000
      - KAFKA_REPLICA_FETCH_MAX_BYTES=10000000
      - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=60000
      - KAFKA_NUM_PARTITIONS=2
      - KAFKA_DELETE_RETENTION_MS=1000

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    container_name: moon-kafka-manager
    ports:
      - "9000:9000"
    links:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: root
      KM_ARGS: -Djava.net.preferIPv4Stack=true